name: inception

secrets:
  db_root_pass:
    file: ../secrets/db_root_password.txt 
  db_user_pass:
    file: ../secrets/db_user_password.txt
  wp_admin_pass:
    file: ../secrets/wp_admin_password.txt
  wp_user_pass:
    file: ../secrets/wp_user_password.txt
  ftp_pass:
    file: ../secrets/ftp_password.txt

volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mariadb
      o: bind
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind
  redis-data:
  ftp-data:

networks:
  wordpress-network:
  static-network:

services:
  nginx:
    container_name: nginx
    image: nginx:1.0-alpine
    build: requirements/nginx
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - wordpress-network
      - static-network
    depends_on:
      - wordpress
      - static
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    image: mariadb:1.0-alpine
    build: requirements/mariadb
    env_file: .env
    environment:
      DB_ROOT_PASS_FILE: /run/secrets/db_root_pass
      DB_USER_PASS_FILE: /run/secrets/db_user_pass
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - wordpress-network
    restart: unless-stopped
    secrets:
      - db_root_pass
      - db_user_pass

  wordpress:
    container_name: wordpress
    image: wordpress:1.0-alpine
    build:
      context: requirements/wordpress
      args:
        PHP_VERSION: ${PHP_VERSION}
    env_file: .env
    environment:
      WP_ADMIN_PASS_FILE: /run/secrets/wp_admin_pass
      WP_USER_PASS_FILE: /run/secrets/wp_user_pass
      DB_USER_PASS_FILE: /run/secrets/db_user_pass
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - wordpress-network
    depends_on:
      - mariadb
      - redis
    restart: unless-stopped
    secrets:
      - wp_admin_pass
      - wp_user_pass
      - db_user_pass

  adminer:
    container_name: adminer
    image: adminer:1.0-alpine
    build: requirements/bonus/adminer
    env_file: .env
    networks:
      - wordpress-network
    depends_on:
      - mariadb
    restart: unless-stopped

  static:
    container_name: static
    image: static:1.0-alpine
    build: requirements/bonus/static
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    networks:
      - static-network
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:1.0-alpine
    build: requirements/bonus/redis
    volumes:
      - redis-data:/data
    networks:
      - wordpress-network
    restart: unless-stopped

  ftp:
    container_name: ftp
    image: ftp:1.0-alpine
    build: requirements/bonus/ftp
    env_file: .env
    environment:
      FTP_PASS_FILE: /run/secrets/ftp_pass
    ports:
      - "2223:22"
    volumes:
      - wordpress-data:/home/${FTP_USER}/wordpress
      - ftp-data:/etc/ssh
    networks:
      - wordpress-network
    restart: unless-stopped
    secrets:
      - ftp_pass

  mailhog:
    container_name: mailhog
    image: mailhog:1.0-alpine
    build: requirements/bonus/mailhog
    ports:
      - "1025:1025" # SMTP
    networks:
      - wordpress-network
    restart: unless-stopped

